
GET http://localhost:3000/api/usuario

###
GET http://localhost:3000/api/usuario?username=ja


###
POST http://localhost:3000/api/usuario
content-type: application/json

{
    "username": "jaime",
    "email": "jaime@test.mx",
    "password": "jaim",
    "sexo": "M",
    "hobbies": ["CSS", "Node"]
}